services:
  - type: web
    name: task-agent
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "PYTHONPATH=. gunicorn app:app"
    buildFilter:
      paths:
        - "**/*"
    envVars:
      - key: PYTHONPATH
        value: "."

