services:
  - type: web
    name: task-agent
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    buildFilter:
      paths:
        - "**/*"
    envVars:
      - fromDotEnv: true

